services:
  mcp-server:
    container_name: mcp-server
    image: mcp-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/.env
    volumes:
      - ./app:/root_project/app
      - type: bind
        source: ./config/.env
        target: /root_project/config/.env
        bind:
          create_host_path: false
    ports:
      - 8000:8000
    stdin_open: true
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - bootstrap.memory_lock=true
      - TZ=UTC
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure
